name: Validate
on: [push, pull_request]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --dangerously-allow-all-builds
      - name: Build and validate
        run: pnpm validate
        env:
          FORCE_COLOR: "true"
